[package]
version = "0.1.0"
name = "seed_rs_org"
repository = "https://github.com/MartinKavik/seed-rs.org"
authors = ["Martin Kavík <martin@kavik.cz>", "David O'Connor <david.alan.oconnor@gmail.com>"]
description = "Rust framework for creating fast and reliable web apps"
categories = ["wasm", "rust", "tailwindcss", "seed", "docs", "website"]
license = "MIT"
readme = "./README.md"
edition = "2018"

build = "build.rs"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
pulldown-cmark = "^0.6.0"

[dev-dependencies]
wasm-bindgen-test = "^0.2.50" # sync with `wasm-bindgen`

[dependencies]
wasm-bindgen = "^0.2.50" # sync with `wasm-bindgen-test`
serde = { version = "^1.0.102", features = ['derive'] }
serde_json = "^1.0.41"
#seed = "0.4.2"
seed = { git = "https://github.com/David-OConnor/seed", branch="master" }
#seed = { path = "../../seed" }

[dependencies.web-sys]
version = "^0.3.28"
features = [
  "ScrollToOptions",
  "Navigator",
]

[profile.release]
lto = true
opt-level = 's'
